import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/satoshi.css";
import "./css/style.css";
import React, { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yaskawa",
  // description: "Generated by create next app",x
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
